config/routes.rb
Rails.application.routes.draw do
  resources :covers
  devise_for :users
  root 'covers#index'

  get 'home/about'

  get 'home/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cover.rb
class Cover < ApplicationRecord
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/ ,
  :storage => :cloudinary
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :covers
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if:
:devise_controller?
protected
def configure_permitted_parameters
#  devise_parameter_sanitizer.for(:sign_up) << :name
#  devise_parameter_sanitizer.for(:account_update) << :name
devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
devise_parameter_sanitizer.permit(:account_update, keys: [:name])
end
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  before_action :set_cover, only: [:show, :edit, :update, :destroy]
  # Uwierzyteknianie do czynności związanych z okładkami
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /covers
  # GET /covers.json
  def index
    @covers = Cover.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
  end

  # GET /covers/1
  # GET /covers/1.json
  def show
  end

  # GET /covers/new
  def new
    @cover = current_user.covers.build
  end

  # GET /covers/1/edit
  def edit
  end

  # POST /covers
  # POST /covers.json
  def create
    @cover = current_user.covers.build(cover_params)

    respond_to do |format|
      if @cover.save
        format.html { redirect_to @cover, notice: 'Cover was successfully created.' }
        format.json { render :show, status: :created, location: @cover }
      else
        format.html { render :new }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /covers/1
  # PATCH/PUT /covers/1.json
  def update
    respond_to do |format|
      if @cover.update(cover_params)
        format.html { redirect_to @cover, notice: 'Cover was successfully updated.' }
        format.json { render :show, status: :ok, location: @cover }
      else
        format.html { render :edit }
        format.json { render json: @cover.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /covers/1
  # DELETE /covers/1.json
  def destroy
    @cover.destroy
    respond_to do |format|
      format.html { redirect_to covers_url, notice: 'Cover was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cover
      @cover = Cover.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cover_params
      params.require(:cover).permit(:description, :image, :name)
    end

    def correct_user
      @cover = current_user.covers.find_by(id: params[:id])
      redirect_to covers_path, notice: "Nie jesteś uprawniony do edycji tej okładki" if @cover.nil?
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/covers/_form.html.erb
<%= form_for @cover, html: { multipart: true } do |f| %>
  <% if cover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cover.errors.count, "error") %> prohibited this cover from being saved:</h2>

      <ul>
      <% cover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <%= f.label :image, "Obraz" %>
  <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/covers/edit.html.erb
<h1>Editing Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Show', @cover %> |
<%= link_to 'Back', covers_path %>

app/views/covers/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "panel panel-default">
  <div class = "panel-body"
    <div id="covers" class="transitions-enabled">
       <% @covers.each do |cover| %>
        <div class="box">
          <div class="panel panel-default">
            <%= link_to image_tag(cover.image.url(:medium)), cover %>
            <div class="panel-body">
            <%= cover.description %><br/>
            <br/><strong><%= cover.user.name if cover.user %></strong>
            <br/>
            </div>
            <% if cover.user == current_user %>
            <div class="panel-footer">
            <%= link_to 'Edycja', edit_cover_path(cover) %><br/>
            <%= link_to 'Usuwanie', cover, method: :delete, data: { confirm: 'Na pewno?' } %><br/>
          </div>
            <%end%>
          </div>
          </div>
        <% end %>
    </div>
  </div>
  <div class = "panel-footer">
    <div class= "center">
      <%= will_paginate @covers, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/covers/new.html.erb
<h1>New Cover</h1>

<%= render 'form', cover: @cover %>

<%= link_to 'Back', covers_path %>

app/views/covers/show.html.erb
  <div class="row">
   <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
     <div class="panel-heading center"><%= image_tag @cover.image.url(:medium) %><br/>
     </div>
     <div class="panel-body">
  <strong>Opis:</strong>
  <%= @cover.description %>
</p>
<br/><%= @cover.user.name %><br/>
<% if @cover.user == current_user %>
<%= link_to 'Edycja', edit_cover_path(@cover) %> |
<%end%>
<%= link_to 'Wstecz', covers_path %>
    </div>
   </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">

<div class="container">

<!-- Brand and toggle get grouped for better mobile
display -->
<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data- 6 toggle="collapse" data-target="#bs-example-navbar-collapse-1">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>

</button>


<%= link_to 'LP Covers', root_path, class: 'navbar-brand' %>
</div>


<!-- Collect the nav links, forms, and other
content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<ul class="nav navbar-nav navbar-right">

<li><%= link_to 'Strona główna', root_path %></li>
<li><%= link_to 'O mnie', home_about_path %></li>

<li><%= link_to 'Okładki', covers_path %></li>
<!-- Odnośniki do stron dostępnych w zależności od statusu użytkownika -->
<% if user_signed_in? %>
<li><%= link_to 'Dodaj okładkę', new_cover_path %></li>
<li><%= link_to 'Edycja profilu', edit_user_registration_path %></li>
<li><%= link_to 'Wylogowanie', destroy_user_session_path, method: :delete %></li>
<% else %>
<li><%= link_to "Logowanie", new_user_session_path %></li>
<li><%= link_to "Rejestracja", new_user_registration_path %></li>
<% end %>
<li><%= link_to 'Kontakt', home_contact_path %></li>
</ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>
<p>Find me in app/views/home/contact.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>LpCovers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Dołączenie pliku nagłówka do wszystkich stron aplikacji -->
    <%= render 'home/header' %>
    <!-- Umieszczenie treści stron w kontenerze -->
    <div class="container">
    <!-- Kod do obsługi powiadomień z devise -->
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
      <%end%>
    <%= yield %>
  </div>
  </body>
</html>